Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

require:
  - rubocop-performance
  - rubocop-rspec

Rails:
  Enabled: true

RSpec:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

Performance:
  Enabled: true

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '**/*.gemspec'

Style/BlockDelimiters:
  Enabled: true

RSpec/MessageSpies:
  Enabled: false